### ISSUE TITLE
Add WKWebView support

### ISSUE THREAD

**Issue by acadet** [coshx/caravel#32]

**Comment by danmerino** [comment]
+1

**Comment by kvijayan** [comment]
+1

**Comment by aty083** [comment]
+1

**Comment by danmerino** [comment]
@acadet Would you like some help with this enhancement?

**Comment by acadet** [comment]
Hey @danmerino, thank you for offering your help :)

Well, as the `WKWebView` JS interface is similar to the one in Android, and [Drekkar](https://github.com/coshx/drekkar) is on alpha production, it should not be a big deal for adding this support. However, I will appreciate some help for reviewing! I can tag you in the PR as soon as it is available.

**Comment by danmerino** [comment]
@acadet sounds great :+1:

**Comment by acadet** [comment]
Ok guys, a beta version (1.1.0-beta) has been released, including the `WKWebView` support. Check out the README to know how to use it.

Let me know how it goes, here or in the Gitter room.

**Comment by acadet** [comment]
Tested and verified. Hence, closing the issue.
