### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [coshx/caravel#38]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by acadet** [comment]
@lfarah Feel free to open a PR, I don't have time to support this lib anymore :/

**Comment by btaitelb** [comment]
@lfarah I've pushed out version v1.2.0 which upgrades to swift3

**Comment by lfarah** [comment]
Awesome! Thank you so much 👍
