### ISSUE TITLE
only works on initial web view.

### ISSUE THREAD

**Issue by ded** [coshx/caravel#4]
Hi,
I'm building a tool that allows editing a document in a webview with a native toolbar. Everything works fine the first time around, but if I dismiss a view controller, then reload it again (creating a new post), none of the events work anymore.

I have this

``` swift
override func viewDidLoad() {
  self.wv!.frame = CGRectMake(0, 65, self.view.bounds.width, self.view.bounds.height - 50)
  self.wv = UIWebView()
  self.view.addSubview(self.wv!)

  Caravel.get("editor", webView: self.wv!).whenReady() { bus in
    bus.register("highlight") { name, data in
      // all is good here!
    }
  }
}
```

``` js
editor.on('highlight', function () {
  Caravel.get("editor").post('highlight')
})
```

As mentioned, it all works great until I attempt to load it the second time around. Any ideas?

**Comment by acadet** [comment]
Hi Dustin!

Thank you for your interest in Caravel!
The issue you pointed out should have been fixed in the latest release. Please let us know how it goes :)

**Comment by ded** [comment]
i'll give it a try. btw I got it to eventually work — I think the main issue is that webView's cache all the resources that get requested, thus I needed to reload my `caravel.min.js` file...

So in my webpage I did the following:

``` jade
head
  script(src='/js/caravel.min.js?no_cache=' + Math.random())
body
  // body content
```

**Comment by acadet** [comment]
Actually, I found out the origin of the issue was in the Swift part. When reloading a controller, the `UIWebView` instance may change. So, if that happens, the bus should watch the new instance instead of the former one.

**Comment by ded** [comment]
gotcha. perhaps i'll revert a few of my changes then :)
