### ISSUE TITLE
bus.post("ev", optionalVar)

### ISSUE THREAD

**Issue by ded** [coshx/caravel#6]
Heyo. Me again.

I had an issue when that I post an optional var, it posts the `Optional()` wrapper around it to the webview.

Eg:

``` swift
bus.post("html", aString: self.html!)
```

``` js
MyListener.register('html', function (name, html) {
  alert(html) // verbatim: "Optional('<p>hello world</p>')"
})
```

it's a little bogus — any thoughts aside from unwrapping the "Optional()" text around the string on the JS side?

**Comment by acadet** [comment]
Hey Dustin, thanks for playing around!

However, I did not succeed in reproducing your issue. I ran different tests by posting optional values, and they were all successful. What is the value of your `html` Swift field?

**Comment by acadet** [comment]
Any news on this issue?
