### ISSUE TITLE
IOS 9

### ISSUE THREAD

**Issue by timbielawski** [coshx/caravel#7]
Is the project still being maintained ? We need some changes for IOS 9

**Comment by acadet** [comment]
I have not looked at the iOS9 support so far. What issue do you have?

Also, feel free to contribute to the project ;)

**Comment by timbielawski** [comment]
Hi,

ok will do I have done a quick fix to get it done, I will issue a pull
request when done

thanks!
Tim

**Comment by acadet** [comment]
Thanks for your help! Do not hesitate if you have any question ;)

**Comment by acadet** [comment]
Hey @timbielawski, I just pushed a new version that should support iOS 9. Let me know how it goes.

**Comment by timbielawski** [comment]
excellent thank-you!

**Comment by acadet** [comment]
@timbielawski Can I close this ticket?

**Comment by timbielawski** [comment]
yeah and thanks for your update

**Comment by acadet** [comment]
You're welcome ;)
